import type { Member, Column, Task } from '../types';

export const TEAM: Member[] = [
  { id: 'u1', name: 'Andi',  color: '#4f6ef7' },
  { id: 'u2', name: 'Budi',  color: '#7c3aed' },
  { id: 'u3', name: 'Citra', color: '#10b981' },
  { id: 'u4', name: 'Dina',  color: '#f59e0b' },
  { id: 'u5', name: 'Eko',   color: '#ef4444' },
  { id: 'u6', name: 'Fani',  color: '#ec4899' },
];

export const DEFAULT_COLUMNS: Column[] = [
  { id: 'todo',    name: 'To Do'   },
  { id: 'doing',   name: 'Doing'   },
  { id: 'review',  name: 'Review'  },
  { id: 'done',    name: 'Done'    },
  { id: 'rework',  name: 'Rework'  },
];

export const LABEL_OPTIONS = [
  { value: 'Feature',   bg: '#eff6ff', color: '#2563eb' },
  { value: 'Bug',       bg: '#fef2f2', color: '#dc2626' },
  { value: 'Issue',     bg: '#fff7ed', color: '#c2410c' },
  { value: 'Undefined', bg: '#f3f4f6', color: '#6b7280' },
] as const;

export const PRIORITY_OPTIONS = [
  { value: 'Low',    color: '#10b981' },
  { value: 'Medium', color: '#f59e0b' },
  { value: 'High',   color: '#ef4444' },
] as const;

export const DUMMY_COVERS = [
  'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&q=80',
  'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=400&q=80',
  'https://images.unsplash.com/photo-1497366216548-37526070297c?w=400&q=80',
  'https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=400&q=80',
];

export const DEFAULT_TASKS: Task[] = [
  {
    id: 't1',
    title: 'Research for a podcast and video website',
    desc: 'Research competitors and best practices for podcast platforms.',
    column: 'todo',
    assignees: ['u1', 'u2'],
    due: '2025-08-08',
    label: 'Feature',
    priority: 'Medium',
    checklist: [
      { id: 's1', text: 'Research competitors', done: true },
      { id: 's2', text: 'Create mood board', done: false },
    ],
    attachments: [{ id: 'a1', name: 'research.pdf' }],
    cover: '',
    done: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 't2',
    title: 'Debug checkout process for the e-commerce website',
    desc: 'Fix bugs in the checkout flow reported by QA team.',
    column: 'todo',
    assignees: ['u1', 'u2', 'u3'],
    due: '2025-10-19',
    label: 'Bug',
    priority: 'High',
    checklist: [
      { id: 's3', text: 'Reproduce the bug', done: true },
      { id: 's4', text: 'Fix payment gateway', done: false },
      { id: 's5', text: 'Write unit test', done: false },
    ],
    attachments: [{ id: 'a2', name: 'bug-report.pdf' }],
    cover: DUMMY_COVERS[2],
    done: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 't3',
    title: 'Design wireframes for the landing page revamp',
    desc: 'Create high-fidelity wireframes for the new landing page.',
    column: 'doing',
    assignees: ['u3', 'u4'],
    due: '2025-08-12',
    label: 'Feature',
    priority: 'High',
    checklist: [
      { id: 's6', text: 'Sketch low-fi wireframes', done: true },
      { id: 's7', text: 'Design high-fi mockups', done: false },
    ],
    attachments: [{ id: 'a3', name: 'wireframes.fig' }],
    cover: DUMMY_COVERS[1],
    done: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 't4',
    title: 'Install and set up a marketing tool for team operations',
    desc: 'Evaluate and integrate marketing automation tools.',
    column: 'doing',
    assignees: ['u1', 'u2', 'u3'],
    due: '2025-08-14',
    label: 'Undefined',
    priority: 'Low',
    checklist: [],
    attachments: [],
    cover: '',
    done: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 't5',
    title: 'Create and refine logo designs for the UI brand',
    desc: 'Design multiple logo concepts and refine based on feedback.',
    column: 'review',
    assignees: ['u3', 'u4'],
    due: '2025-08-10',
    label: 'Issue',
    priority: 'Medium',
    checklist: [],
    attachments: [],
    cover: DUMMY_COVERS[0],
    done: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 't6',
    title: 'Create an icon library for the project',
    desc: 'Design and organize a reusable icon library.',
    column: 'review',
    assignees: ['u1', 'u2'],
    due: '2025-08-08',
    label: 'Feature',
    priority: 'Low',
    checklist: [
      { id: 's8', text: 'Define icon style', done: true },
      { id: 's9', text: 'Export all icons as SVG', done: false },
    ],
    attachments: [{ id: 'a4', name: 'icons.zip' }],
    cover: '',
    done: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 't7',
    title: 'Create the Email Page layout and necessary components',
    desc: 'Build the email template layout with reusable components.',
    column: 'done',
    assignees: ['u1', 'u2'],
    due: '2025-08-15',
    label: 'Feature',
    priority: 'Medium',
    checklist: [],
    attachments: [],
    cover: '',
    done: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 't8',
    title: 'Blog Edit Page Modification and Playlist Page Design',
    desc: 'Modify the blog edit page and design the playlist page.',
    column: 'rework',
    assignees: ['u3', 'u4'],
    due: '2025-08-08',
    label: 'Feature',
    priority: 'High',
    checklist: [
      { id: 's10', text: 'Update blog editor UI', done: true },
      { id: 's11', text: 'Design playlist layout', done: false },
    ],
    attachments: [],
    cover: DUMMY_COVERS[3],
    done: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 't9',
    title: 'Plan and execute training sessions for new hires',
    desc: 'Organize onboarding and training schedule for new team members.',
    column: 'rework',
    assignees: ['u1', 'u2'],
    due: '2025-08-09',
    label: 'Issue',
    priority: 'Medium',
    checklist: [
      { id: 's12', text: 'Prepare training materials', done: false },
      { id: 's13', text: 'Schedule sessions', done: false },
    ],
    attachments: [{ id: 'a5', name: 'training-plan.docx' }],
    cover: '',
    done: false,
    createdAt: new Date().toISOString(),
  },
];

export const ACCENT = '#4f6ef7';